FistRazorPageApp/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FistRazorPageApp.Models
{
    public class User
    {
        public User()
        {
            this.Id = _id++;
        }
        public int Id { get; set; }

        public static int _id { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Name { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

    }
}

FistRazorPageApp/Models/UserDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FistRazorPageApp.Models
{
    public class UserDbContext:DbContext
    {
        public UserDbContext(DbContextOptions<UserDbContext> dbContextOptions):base(dbContextOptions)
        {

        }
        public DbSet<User> Users { get; set; }
    }
}

FistRazorPageApp/Models/UserLoginModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FistRazorPageApp.Models
{
    public class UserLoginModel
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

FistRazorPageApp/Pages/Default.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FistRazorPageApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyUser = FistRazorPageApp.Models;
namespace FistRazorPageApp.Pages
{
    public class DefaultModel : PageModel
    {
        private readonly UserDbContext _userDbContext;
        public DefaultModel(UserDbContext userDbContext)
        {
            _userDbContext = userDbContext;
        }

        [BindProperty()]
        public User RegisterUser { get; set; }

        public void OnGet()
        {
            
        }
        public async Task<IActionResult> OnPostAsync()
        {
           
            if (ModelState.IsValid)
            {
              MyUser.User currentUser = await _userDbContext.Users.Where(x => x.Email == RegisterUser.Email).SingleOrDefaultAsync();
                if(currentUser==null)
                {
                   await _userDbContext.Users.AddAsync(RegisterUser);
                   await _userDbContext.SaveChangesAsync();
                    return RedirectToPage("/Login");
                }
                else
                {
                    ModelState.AddModelError("", "this user already exists");
                }
            }
            return Page();
        }
    }
}

FistRazorPageApp/Pages/List.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using FistRazorPageApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyUser = FistRazorPageApp.Models;

namespace FistRazorPageApp.Pages
{
    public class ListModel : PageModel
    {
        private readonly UserDbContext _userDbContext;

        public ListModel(UserDbContext userDbContext)
        {
            CurrentUser = new User();
            _userDbContext = userDbContext;
        }

       
        public IEnumerable<User> Users { get; private set; }

        public MyUser.User CurrentUser { get; set; }

        public async Task  OnGetAsync()
        {
          Users = await _userDbContext.Users.ToListAsync();
        }
        
        public async Task<IActionResult> OnPostEditAsync(int id, string username, string useremail, string password)
        {  
            MyUser.User currentUser = await _userDbContext.Users.FindAsync(id);
            if (currentUser != null)
            {
                currentUser.Email = useremail;
                currentUser.Name = username;
                currentUser.Password = password; 
                await this._userDbContext.SaveChangesAsync();
            }
            Users = await _userDbContext.Users.ToListAsync();
            return Page();
        }

        public async Task<IActionResult> OnGetEditAsync(int id)
        {
            Users = await _userDbContext.Users.ToListAsync();
            MyUser.User currentUser = await _userDbContext.Users.FindAsync(id);
            if (currentUser != null)
            {
                CurrentUser = currentUser;
            }
            
                return Page();
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            MyUser.User currentUser = await _userDbContext.Users.FindAsync(id);
            if (currentUser != null)
            {
                _userDbContext.Users.Remove(currentUser);
               await _userDbContext.SaveChangesAsync();

            }
            Users = await _userDbContext.Users.ToListAsync();
            return Page();

        }

    }
}

FistRazorPageApp/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FistRazorPageApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyUser = FistRazorPageApp.Models;

namespace FistRazorPageApp.Pages
{
    public class LoginModel : PageModel
    {
        private readonly UserDbContext _userDbContext;
        public LoginModel(UserDbContext userDbContext)
        {
            _userDbContext = userDbContext;
        }

        [BindProperty()]
        public UserLoginModel UserLogin { get; set; }

        public void OnGet()
        {

        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                MyUser.User currentUser = await _userDbContext.Users.Where(x => x.Email == UserLogin.Email && x.Password == UserLogin.Password).FirstOrDefaultAsync();

                if (currentUser ==null)
                {
                    ModelState.AddModelError("", "This user is not valid");
                }
                else
                {
                    return RedirectToPage("/List");
                }
            }
            return Page();
        }
    }
}

FistRazorPageApp/Pages/Default.cshtml
@page "/"
@model FistRazorPageApp.Pages.DefaultModel
@{

    ViewData["Title"] = "Default";
}


<form class="form-horizontal" method="post" asp-page="Default">
    <div asp-validation-summary="ModelOnly"></div>
    <div class="form-group">
        <label asp-for="RegisterUser.Name" class="cols-sm-2 control-label"></label>
        <div class="cols-sm-10">
            <div class="input-group">
                <span class="input-group-addon"><i class="fas fa-user fa" aria-hidden="true"></i></span>
                <input class="form-control" asp-for="RegisterUser.Name" placeholder="Enter your Name" />
                <span asp-validation-for="RegisterUser.Name"></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="RegisterUser.Email" class="cols-sm-2 control-label"></label>
        <div class="cols-sm-10">
            <div class="input-group">
                <span class="input-group-addon"><i class="fas fa-envelope fa" aria-hidden="true"></i></span>
                <input class="form-control" asp-for="RegisterUser.Email" placeholder="Enter your Email" />
                <span asp-validation-for="RegisterUser.Email"></span>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="RegisterUser.Password" class="cols-sm-2 control-label"></label>
        <div class="cols-sm-10">
            <div class="input-group">
                <span class="input-group-addon"><i class="fas fa-lock fa-lg" aria-hidden="true"></i></span>
                <input class="form-control" asp-for="RegisterUser.Password" placeholder="Enter your Password" />
                <span asp-validation-for="RegisterUser.Password"></span>
            </div>
        </div>
    </div>
   
    <div class="form-group ">
        <button type="submit" class="btn btn-primary btn-lg btn-block login-button">Register</button>
    </div>
    <div class="login-register">
        <a asp-action="Login" asp-controller="Account">Login</a>
    </div>
</form>

FistRazorPageApp/Pages/List.cshtml
@page "{handler?}/{id?}"
@model FistRazorPageApp.Pages.ListModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "List";
}
<div class="container">
    <div class="row">
        <div class="col-lg-7">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Password</th>
                        <th>Operations</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Users)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.Email</td>
                            <td>@item.Password</td>
                            <td>
                                <form asp-page="List" asp-page-handler="Edit" method="get" asp-route-id="@item.Id">
                                    <button type="submit" class="btn btn-warning">Edit</button>
                                </form>&nbsp;
                                <form asp-page-handler="Delete" method="post">
                                    <input type="hidden" value="@item.Id" name="Id" />
                                    <button type="submit" class="btn btn-warning">Delete</button>
                                </form>

                        </tr>

                    }
                </tbody>
            </table>
        </div>
       <div class="col-lg-5">
           <form asp-page-handler="Edit"  class="form-horizontal" method="post" asp-page="List">
               <div asp-validation-summary="ModelOnly"></div>
               <div class="form-group">
                   <div class="cols-sm-10">
                       <div class="input-group">
                           <input hidden class="form-control" name="id" asp-for="CurrentUser.Id" value="@Model.CurrentUser.Id" />
                       </div>
                   </div>
               </div>
               <div class="form-group">
                   <label asp-for="CurrentUser.Name" class="cols-sm-2 control-label"></label>
                   <div class="cols-sm-10">
                       <div class="input-group">
                           <span class="input-group-addon"><i class="fas fa-user fa" aria-hidden="true"></i></span>
                           <input class="form-control" name="username" asp-for="CurrentUser.Name" value="@Model.CurrentUser.Name" />
                           <span asp-validation-for="CurrentUser.Name"></span>
                       </div>
                   </div>
               </div>
               <div class="form-group">
                   <label asp-for="CurrentUser.Email" class="cols-sm-2 control-label"></label>
                   <div class="cols-sm-10">
                       <div class="input-group">
                           <span class="input-group-addon"><i class="fas fa-envelope fa" aria-hidden="true"></i></span>
                           <input class="form-control" name="useremail" asp-for="CurrentUser.Email" value="@Model.CurrentUser.Email" />
                           <span asp-validation-for="CurrentUser.Email"></span>
                       </div>
                   </div>
               </div>

               <div class="form-group">
                   <label asp-for="CurrentUser.Password" class="cols-sm-2 control-label"></label>
                   <div class="cols-sm-10">
                       <div class="input-group">
                           <span class="input-group-addon"><i class="fas fa-lock fa-lg" aria-hidden="true"></i></span>
                           <input class="form-control" name="password" asp-for="CurrentUser.Password" value="@Model.CurrentUser.Password" />
                           <span asp-validation-for="CurrentUser.Password"></span>
                       </div>
                   </div>
               </div>

               <div class="form-group ">
                   <button type="submit" class="btn btn-primary btn-lg btn-block login-button">Edit</button>
               </div>
               
           </form>
       </div>
    </div>

</div>

FistRazorPageApp/Pages/Login.cshtml
@page
@model FistRazorPageApp.Pages.LoginModel
@{
    ViewData["Title"] = "Login";
}

<form class="form-horizontal" method="post">
    <div asp-validation-summary="ModelOnly"></div>
    <div class="form-group">
        <label asp-for="UserLogin.Email" class="cols-sm-2 control-label"></label>
        <div class="cols-sm-10">
            <div class="input-group">
                <span class="input-group-addon"><i class="fas fa-envelope fa" aria-hidden="true"></i></span>
                <input class="form-control" asp-for="UserLogin.Email" placeholder="Enter your Email" />
                <span asp-validation-for="UserLogin.Email"></span>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="UserLogin.Password" class="cols-sm-2 control-label"></label>
        <div class="cols-sm-10">
            <div class="input-group">
                <span class="input-group-addon"><i class="fas fa-lock fa-lg" aria-hidden="true"></i></span>
                <input class="form-control" asp-for="UserLogin.Password" placeholder="Enter your Password" />
                <span asp-validation-for="UserLogin.Password"></span>
            </div>
        </div>
    </div>

   
    <div class="form-group ">
        <button type="submit" class="btn btn-primary btn-lg btn-block login-button">Login</button>
    </div>
    <div class="login-register">
        <p>Dont have any account? &nbsp;<a asp-action="Register" asp-controller="Account">Register</a></p>
    </div>
</form>

FistRazorPageApp/Pages/Shared/_AccountLayout.cshtml
<!------ Include the above in your HEAD tag ---------->
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="~/lib/js/jquery-1.11.1.min.js" defer></script>
    <script src="~/lib/js/bootstrap.min.js" defer></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Website Font style -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
    <title>Admin</title>

    <style>
        /*
        /* Created by Filipe Pina
         * Specific styles of signin, register, component
         */
        /*
         * General styles
         */

        body, html {
            height: 100%;
            background-repeat: no-repeat;
            background-color: #d3d3d3;
            font-family: 'Oxygen', sans-serif;
        }

        .main {
            margin-top: 70px;
        }

        h1.title {
            font-size: 50px;
            font-family: 'Passion One', cursive;
            font-weight: 400;
        }

        hr {
            width: 10%;
            color: #fff;
        }

        .form-group {
            margin-bottom: 15px;
        }

        label {
            margin-bottom: 15px;
        }

        input,
        input::-webkit-input-placeholder {
            font-size: 11px;
            padding-top: 3px;
        }

        .main-login {
            background-color: #fff;
            /* shadows and rounded borders */
            -moz-border-radius: 2px;
            -webkit-border-radius: 2px;
            border-radius: 2px;
            -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
            -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
            box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        }

        .main-center {
            margin-top: 30px;
            margin: 0 auto;
            max-width: 330px;
            padding: 40px 40px;
        }

        .login-button {
            margin-top: 5px;
        }

        .login-register {
            font-size: 11px;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row main">
            <div class="panel-heading">
                <div class="panel-title text-center">
                    <h1 class="title">Mozar Register panel</h1>
                    <hr />
                </div>
            </div>
            <div class="main-login main-center">
               @RenderBody()
            </div>
        </div>
    </div>

</body>
</html>

FistRazorPageApp/Pages/Shared/_Layout.cshtml
<!------ Include the above in your HEAD tag ---------->
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="~/lib/js/jquery-1.11.1.min.js" defer></script>
    <script src="~/lib/js/bootstrap.min.js" defer></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Website Font style -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
    <title>Admin</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>